type Data {
  json: String!
}

type Doc {
  id: Id!
  attributes: Data!
  rev: String!
}

type Docs {
  items: [Doc]
  next: String
}

type Link {
  id1: ID!,
  id2: ID!,
}

type Links {
  items: [Link]
  next: String
}

type Mgr {
  type: String
  create(data: Data!): Doc
  get(id: ID!): Doc
  put(id: ID!, rev: String, data: Data!): Doc
  delete(id: ID!, rev: String): Boolean
  all(limit: Int = 10, sortby: String, descending: Boolean = true): Docs
  nextPages(pagesUrl: String): Docs
  find(index: String!, selector: String!, sort: String, fields: string, limit: Int = 10: Docs
  view(view: String, key: String, keys: String, start_key: String, end_key: String, descending: Boolean, group: Boolean = false, group_level: Int, include_docs: Boolean = true, limit: Int = 10): Docs
  serach(keywords: [String]!, selector: String, sort: String, include_docs: Boolean, limit: Int = 10): Docs
  link(type: String!, id: ID!, refID: ID!): Boolean
  unlink(type: String!, id: ID!, refID: ID!): Boolean
  allLinks(type: String!, id: ID!, limit: Int = 10, descending: Boolean = true): Links
  nextLinks(linksUrl: String): Links
}

type Query {
  hello: String
  quoteOfTheDay: String
  random: Float!
  rollThreeDice: [Int]
  rollDice(numDice: Int!, numSides: Int): [Int]
  getDie(numSides: Int): RandomDie
  getMessage(id: ID!): Message
  mgr(type: String): Mgr
}

type Mutation {
  mgr(type: String): Mgr
}
